name: CI

on: [pull_request, push]

jobs:
  build:

    name: Erlang/OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp: [23.2, 22.3]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GMP
      run: sudo apt-get install -y libgmp-dev
    - name: Set up Erlang
      uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: '${{matrix.otp}}'
    - name: Build
      run: rebar3 compile
    - name: Tests
      run: rebar3 eunit
